"""add phone number for user

Revision ID: e42f68e16a04
Revises: 644fb90abf2f
Create Date: 2025-01-31 18:15:06.450679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42f68e16a04'
down_revision: Union[str, None] = '644fb90abf2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=33), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=33),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=33),
               nullable=True)
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
